### ISSUE TITLE
Github actions are not upgraded

### ISSUE THREAD

**Issue by kimmoahola** [liquidz/antq#192]
I have the following GHA yml file:

```
name: TEST
on:
  push:
    branches:
    - "*"
jobs:
  lint:
    steps:
    - uses: actions/checkout@v2


  lint2:
    steps:
    - uses: actions/checkout@v3.0.2
```

My deps.edn looks like this:

```
:deps {...

:aliases {
  :outdated {:replace-deps {com.github.liquidz/antq {:mvn/version "2.2.962"}}
             :main-opts ["-m" "antq.core" "--upgrade" "--force" "--skip=pom"]}
}
```

When I run antq it will output:

```
|                             :file |                                         :name | :current | :latest |
|-----------------------------------+-----------------------------------------------+----------+---------|
|        .github/workflows/test.yml |                              actions/checkout |       v2 |  v3.1.0 |
|                                   |                              actions/checkout |   v3.0.2 |  v3.1.0 |

Available changes:
- https://github.com/actions/checkout/blob/v3.1.0/CHANGELOG.md
Upgraded actions/checkout 'v2' to 'v3' in .github/workflows/test.yml.
Upgraded actions/checkout 'v3.0.2' to 'v3.1.0' in .github/workflows/test.yml.
```

But it will not update those two checkout steps.

And another issue is that the `test.yml` will get bogus content. The lint2 job get duplicated:

```
name: TEST
on:
  push:
    branches:
    - "*"
jobs:
  lint:
    steps:
    - uses: actions/checkout@v2


  lint2:
    steps:
    - uses: actions/checkout@v3.0.2

  lint2:
    steps:
    - uses: actions/checkout@v3.0.2

  lint2:
    steps:
    - uses: actions/checkout@v3.0.2

  lint2:
    steps:
    - uses: actions/checkout@v3.0.2
```

The original test.yml has two empty lines before `lint2:`. If I remove the other empty line then the content is not duplicated (but steps are still not upgraded).

If I add two spaces to the beginning of the lines `- uses:` then antq will upgrade those steps. The original test.yml file is valid yaml (maybe not properly formated, but still valid).

**Comment by liquidz** [comment]
@kimmoahola Thanks for your reporting!
It should be a problem of [liquidz/rewrite-indented](https://github.com/liquidz/rewrite-indented).

I didn't have a good library to rewrite yaml, so I made a simple one.
This library rewrites texts based on indentations only, so the validity of yaml is not checked.

To fix this problem, we need to find or create a library that correctly parses and rewrites yaml.

FYI, If [antlr](https://github.com/antlr/antlr4) had a yaml grammer, I would have wanted to use it.
https://github.com/antlr/grammars-v4

**Comment by seancorfield** [comment]
Just coming here to report something very similar -- I have:

```yaml
      - name: Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.11.1.1208'
```

`antq` spots that it is outdated and offers to upgrade it to 1.11.1.1347 but answering `y` produces no change in the file.

**Comment by liquidz** [comment]
@seancorfield Oh, I could reproduce the problem. Thanks!

**Comment by liquidz** [comment]
It is a bug in [liquidz/rewrite-indented](https://github.com/liquidz/rewrite-indented).
I'll fix :)

**Comment by liquidz** [comment]
@seancorfield I've fixed the problem in v2.5.1095.
By the way, `tools-deps` is deprecated and antq does not support.
https://github.com/DeLaGuardo/setup-clojure/blob/1c76ab0e154379260d7a6ea16b413679abe46785/action.yml#L13-L14

Please use `cli` instead of `tools-deps`.

**Comment by seancorfield** [comment]
Good to know -- thanks!

**Comment by seancorfield** [comment]
Works beautifully, now I've switched to `cli:` -- thank you!

**Comment by devurandom** [comment]
I still encounter the original issue author's problem: When a workflow contains multiple references to `actions/checkout@...` antq will only update one of them (the first?). It will detect that the action could be updated, but confirming with `y` results in no changes in the file.

**Comment by liquidz** [comment]
@devurandom Could you show me your YAML file?
I'll try to reproduce the problem.

**Comment by devurandom** [comment]
I am able to reproduce it with this file:
```yaml
jobs:
  example:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v3
        with:
          repository: antq/example
```
```
❯ tree -a
.
└── .github
    └── workflows
        └── antq-mwe.yml

3 directories, 1 file

❯ clj -Tantq outdated :upgrade true
[##################################################] 1/1
| :file                          | :name            | :current | :latest |
|--------------------------------+------------------+----------+---------|
| .github/workflows/antq-mwe.yml | actions/checkout | v3       | v4.1.1  |

Available changes:
- https://github.com/actions/checkout/blob/v4.1.1/CHANGELOG.md

Do you want to upgrade actions/checkout 'v3' to 'v4' in .github/workflows/antq-mwe.yml (y/n): y
Upgraded actions/checkout 'v3' to 'v4' in .github/workflows/antq-mwe.yml.
```

**Comment by liquidz** [comment]
@devurandom Thanks! I could reproduce the problem.
I'll fix :)

**Comment by liquidz** [comment]
@devurandom Sorry for late work.
I've fixed the problem in [dev](https://github.com/liquidz/antq/tree/dev) branch.
Could you try?

**Comment by liquidz** [comment]
@devurandom Thanks for your confirmation!
Just released [2.7.1147](https://github.com/liquidz/antq/releases/tag/2.7.1147)

**Comment by seancorfield** [comment]
Feels like this can be closed out now?

**Comment by liquidz** [comment]
Thanks!
